version: '3'
services:
    prisma:
        image: prismagraphql/prisma:1.34
        restart: always
        ports:
            - "4466:4466"
        environment:
            PRISMA_CONFIG: |
                port: 4466
                # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
                # managementApiSecret: my-secret
                databases:
                    default:
                        connector: postgres
                        host: postgres
                        user: prisma
                        password: prisma
                        rawAccess: true
                        port: 5432
                        migrations: true

    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: prisma
            POSTGRES_PASSWORD: prisma
        volumes:
            - ./postgres:/var/lib/postgresql/data

    adminer:
        depends_on:
            - postgres
        restart: always
        image: adminer:latest
        ports:
            - 8090:8080


    npm:
        image: node:14.0.0-alpine
        user: node
        entrypoint: npm
        working_dir: /home/node/app
        env_file: .env
        ports:
            - 4000:4000
        volumes:
            - .:/home/node/app

    npx:
        image: node:14.0.0-alpine
        user: node
        entrypoint: npx
        working_dir: /home/node/app
        volumes:
            - .:/home/node/app
