version: "3"

services:
    node:
        image: node:14.0.0-alpine3.11
        user: node
        working_dir: /home/node/app
        stdin_open: true
        tty: true
        volumes:
            - .:/home/node/app

    postgres:
        image: postgres:13.0-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: root
            POSTGRES_USER: root
            POSTGRES_DB: prisma
